In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [69]:
train = pd.read_csv('/content/train_loan (1).csv')

In [70]:
df = train.copy()

In [71]:
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [73]:
#for finding missing values
df.isna().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [74]:
# Replace NaNs with mode for categorical columns
df['Gender'].fillna(df['Gender'].mode()[0], inplace=True)
df['Married'].fillna(df['Married'].mode()[0], inplace=True)
df['Dependents'].fillna(df['Dependents'].mode()[0], inplace=True)
df['Self_Employed'].fillna(df['Self_Employed'].mode()[0], inplace=True)
df['Loan_Amount_Term'].fillna(df['Loan_Amount_Term'].mode()[0], inplace=True)

In [75]:
# Impute missing values in numerical columns with median
df['LoanAmount'].fillna(df['LoanAmount'].median(), inplace=True)

In [76]:
# Impute Credit_History with a new category
df['Credit_History'].fillna('No Credit History', inplace=True)

In [77]:
df.isna().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    object
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(3), int64(1), object(9)
memory usage: 62.5+ KB

In [79]:
# Perform one-hot encoding for categorical variables
df = pd.get_dummies(df, columns=['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed', 'Property_Area'])

In [80]:
# Encode Loan_Status separately since it's the target variable
df['Loan_Status'] = df['Loan_Status'].map({'Y': 1, 'N': 0})

In [81]:
# Encode Credit_History using label encoding since it's binary
df['Credit_History'] = df['Credit_History'].map({'Yes': 1, 'No': 0, 'No Credit History': -1})

In [82]:
df.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001002,5849,0.0,128.0,360.0,NaN,1,False,True,True,...,False,False,False,True,False,True,False,False,False,True
1,LP001003,4583,1508.0,128.0,360.0,NaN,0,False,True,False,...,True,False,False,True,False,True,False,True,False,False
2,LP001005,3000,0.0,66.0,360.0,NaN,1,False,True,False,...,False,False,False,True,False,False,True,False,False,True
3,LP001006,2583,2358.0,120.0,360.0,NaN,1,False,True,False,...,False,False,False,False,True,True,False,False,False,True
4,LP001008,6000,0.0,141.0,360.0,NaN,1,False,True,True,...,False,False,False,True,False,True,False,False,False,True

In [83]:
# Drop rows with NaN values in the 'Credit_History' column
df.dropna(subset=['Credit_History'], inplace=True)

In [84]:
# Reset the index after dropping rows
df.reset_index(drop=True, inplace=True)

In [85]:
df.head()

,Loan_ID,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Gender_Female,Gender_Male,Married_No,...,Dependents_1,Dependents_2,Dependents_3+,Education_Graduate,Education_Not Graduate,Self_Employed_No,Self_Employed_Yes,Property_Area_Rural,Property_Area_Semiurban,Property_Area_Urban
0,LP001034,3596,0.0,100.0,240.0,-1.0,1,False,True,True,...,True,False,False,False,True,True,False,False,False,True
1,LP001052,3717,2925.0,151.0,360.0,-1.0,0,False,True,False,...,True,False,False,True,False,True,False,False,True,False
2,LP001091,4166,3369.0,201.0,360.0,-1.0,0,False,True,False,...,True,False,False,True,False,True,False,False,False,True
3,LP001123,2400,0.0,75.0,360.0,-1.0,1,False,True,False,...,False,False,False,True,False,True,False,False,False,True
4,LP001264,3333,2166.0,130.0,360.0,-1.0,1,False,True,False,...,False,False,True,False,True,False,True,False,True,False

In [86]:
#drop loan_id from dataset
df.drop(columns=['Loan_ID'], inplace=True)

In [87]:
# Split data into features and target variable
x = df.drop(columns=['Loan_Status'])
y = df['Loan_Status']

In [88]:
from sklearn.model_selection import train_test_split

In [89]:
# Split data into training and testing sets
x_train,x_test,y_train,y_test = train_test_split(x.values,y,test_size = 0.3,random_state = 42)

In [90]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.25.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from xgboost) (1.11.4)

In [91]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.10/dist-packages (1.2.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.10/dist-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.10/dist-packages (from catboost) (3.7.1)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from catboost) (1.25.2)
Requirement already satisfied: pandas>=0.24 in /usr/local/lib/python3.10/dist-packages (from catboost) (2.0.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.10/dist-packages (from catboost) (1.11.4)
Requirement already satisfied: plotly in /usr/local/lib/python3.10/dist-packages (from catboost) (5.15.0)
Requirement already satisfied: six in /usr/local/lib/python3.10/dist-packages (from catboost) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (4.51.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (24.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib->catboost) (3.1.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly->catboost) (8.2.3)

In [92]:
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor

In [93]:
#initialize the models
models = {'Random Forest': RandomForestRegressor(), 'XGB Regressor': XGBRegressor(),'Catboost': CatBoostRegressor(verbose=0)}

In [95]:
#train the models
for name,model in models.items():
  model.fit(x_train,y_train)
  print(name + 'trained')

Random Foresttrained
XGB Regressortrained
Catboosttrained

In [96]:
from sklearn.metrics import mean_squared_error

In [97]:
#finding the mse
for name,model in models.items():
  y_pred = model.predict(x_test)
  mse = mean_squared_error(y_test,y_pred)
  print(name + 'MSE {:.2f}'.format(mse))

Random ForestMSE 0.26
XGB RegressorMSE 0.39
CatboostMSE 0.26